CREATE DATABASE Gastronomia
go

USE Gastronomia

-- Table RECETAS

CREATE TABLE [RECETAS]
(
    [ID_RECETA]          Bigint IDENTITY NOT NULL,
    [NOMBRE_RECETA]      Varchar(30)     NOT NULL,
    [DESCRIPCION]        Varchar(250)    NOT NULL,
    [TIEMPO_PREPARACION] Varchar(10)     NOT NULL,
    [TIEMPO_COCCION]     Varchar(10)     NOT NULL,
    [PORCIONES]          Tinyint         NOT NULL,
    [DIFICULTAD]         Tinyint         NOT NULL,
    [ID_CATEGORIA]       Bigint          NOT NULL,
    [ID_PERSONA]         Bigint          NOT NULL
)
go
insert into RECETAS (NOMBRE_RECETA, DESCRIPCION, TIEMPO_PREPARACION, TIEMPO_COCCION, PORCIONES, DIFICULTAD,
                     ID_CATEGORIA, ID_PERSONA)
values ('Brownies de chocolate',
        'Un brownie es un bizcocho de chocolate pequeño, típico de la gastronomía de Estados Unidos.', '30 minutos',
        '25 minutos', 4, 3, 1, 1)
-- Add keys for table RECETAS

ALTER TABLE [RECETAS]
    ADD CONSTRAINT [Unique_Identifier1] PRIMARY KEY ([ID_RECETA])
go

-- Table CATEGORIAS

CREATE TABLE [CATEGORIAS]
(
    [ID_CATEGORIA]     Bigint IDENTITY NOT NULL,
    [NOMBRE_CATEGORIA] Varchar(15)     NOT NULL,
    [DESCRIPCION]      Varchar(250)    NOT NULL
)
go
insert into CATEGORIAS (NOMBRE_CATEGORIA, DESCRIPCION)
values ('Parrillas', 'Todo tipo de parrillas.')
-- Add keys for table CATEGORIAS

ALTER TABLE [CATEGORIAS]
    ADD CONSTRAINT [Unique_Identifier2] PRIMARY KEY ([ID_CATEGORIA])
go

-- Table PERSONAS

CREATE TABLE [PERSONAS]
(
    [ID_PERSONA]       Bigint IDENTITY NOT NULL,
    [NOMBRES]          Varchar(30)     NOT NULL,
    [APELLIDO_PATERNO] Varchar(15)     NOT NULL,
    [APELLIDO_MATERNO] Varchar(15)     NOT NULL,
    [SEXO]             Char(1)         NOT NULL,
    [FECHA_NACIMIENTO] Date            NOT NULL,
    [DIRECCION]        Varchar(100)    NOT NULL,
    [TELEFONO]         Char(9)         NOT NULL,
    [CORREO]           Varchar(50)     NOT NULL,
    [USERNAME]         VARCHAR(15)     NOT NULL,
    [CONTRASENA]       VARCHAR(15)     NOT NULL
)
go

-- Add keys for table PERSONAS

ALTER TABLE [PERSONAS]
    ADD CONSTRAINT [Unique_Identifier3] PRIMARY KEY ([ID_PERSONA])
go

-- Table CARGOS

CREATE TABLE [CARGOS]
(
    [ID_CARGO]    Bigint IDENTITY NOT NULL,
    [TITULO]      Varchar(15)     NOT NULL,
    [DESCRIPCION] Varchar(250)    NOT NULL
)
go

-- Add keys for table CARGOS

ALTER TABLE [CARGOS]
    ADD CONSTRAINT [Unique_Identifier4] PRIMARY KEY ([ID_CARGO])
go

-- Table CURSOS

CREATE TABLE [CURSOS]
(
    [ID_CURSO]     Bigint IDENTITY NOT NULL,
    [NOMBRE]       Varchar(30)     NOT NULL,
    [DESCRIPCION]  Varchar(250)    NULL,
    [FECHA_INICIO] Varchar(15)     NOT NULL,
    [FECHA_FIN]    Varchar(15)     NOT NULL,
    [CUPOS]        Smallint        NOT NULL,
    [HORARIO]      Varchar(250)    NOT NULL,
    [COSTO]        Money           NOT NULL
)
go

-- Add keys for table CURSOS

ALTER TABLE [CURSOS]
    ADD CONSTRAINT [Unique_Identifier5] PRIMARY KEY ([ID_CURSO])
go

-- Table PRODUCTOS

CREATE TABLE [PRODUCTOS]
(
    [ID_PRODUCTO] Bigint IDENTITY NOT NULL,
    [NOMBRE]      Varchar(15)     NOT NULL,
    [DESCRIPCION] Varchar(250)    NOT NULL,
    [STOCK]       Smallint        NOT NULL
)
go

-- Add keys for table PRODUCTOS

ALTER TABLE [PRODUCTOS]
    ADD CONSTRAINT [Unique_Identifier6] PRIMARY KEY ([ID_PRODUCTO])
go

-- Table INGREDIENTES

CREATE TABLE [INGREDIENTES]
(
    [ID_INGREDIENTE]   Bigint         NOT NULL,
    [CANTIDAD]         DECIMAL(10, 2) NOT NULL,
    [ID_UNIDAD_MEDIDA] Bigint         NOT NULL,
    [ID_RECETA]        Bigint         NOT NULL
)
go

-- Add keys for table INGREDIENTES

ALTER TABLE [INGREDIENTES]
    ADD CONSTRAINT [Unique_Identifier7] PRIMARY KEY ([ID_INGREDIENTE], [ID_RECETA])
go

-- Table UNIDAD_MEDIDA

CREATE TABLE [UNIDAD_MEDIDA]
(
    [ID_UNIDAD_MEDIDA] Bigint IDENTITY NOT NULL,
    [NOMBRE]           Varchar(25)     NOT NULL,
    [ABREVIATURA]      Varchar(5)      NOT NULL
)
go

-- Add keys for table UNIDAD_MEDIDA

ALTER TABLE [UNIDAD_MEDIDA]
    ADD CONSTRAINT [Unique_Identifier8] PRIMARY KEY ([ID_UNIDAD_MEDIDA])
go

-- Table PROVEEDOR

CREATE TABLE [PROVEEDOR]
(
    [ID_PROVEEDOR] Bigint IDENTITY NOT NULL,
    [NOMBRE]       Varchar(30)     NOT NULL,
    [CONTACTO]     Varchar(50)     NOT NULL,
    [TELEFONO]     Char(9)         NOT NULL
)
go

-- Add keys for table PROVEEDOR

ALTER TABLE [PROVEEDOR]
    ADD CONSTRAINT [Unique_Identifier9] PRIMARY KEY ([ID_PROVEEDOR])
go

-- Table PROVEEDOR_PRODUCTO

CREATE TABLE [PROVEEDOR_PRODUCTO]
(
    [ID_PROVEEDOR] Bigint NOT NULL,
    [ID_PRODUCTO]  Bigint NOT NULL,
    [PRECIO]       Money  NOT NULL
)
go

-- Add keys for table PROVEEDOR_PRODUCTO

ALTER TABLE [PROVEEDOR_PRODUCTO]
    ADD CONSTRAINT [Unique_Identifier10] PRIMARY KEY ([ID_PROVEEDOR], [ID_PRODUCTO])
go

-- Table GRUPO

CREATE TABLE [GRUPO]
(
    [ID_GRUPO]    Bigint IDENTITY NOT NULL,
    [CODIGO]      Varchar(10)     NOT NULL,
    [ID_PROFESOR] Bigint          NOT NULL,
    [ID_CURSO]    Bigint          NOT NULL
)
go

-- Add keys for table GRUPO

ALTER TABLE [GRUPO]
    ADD CONSTRAINT [Unique_Identifier11] PRIMARY KEY ([ID_GRUPO])
go

-- Table CARGO_PERSONA

CREATE TABLE [CARGO_PERSONA]
(
    [ID_CARGO]   Bigint NOT NULL,
    [ID_PERSONA] Bigint NOT NULL
)
go

-- Add keys for table CARGO_PERSONA

ALTER TABLE [CARGO_PERSONA]
    ADD CONSTRAINT [Unique_Identifier12] PRIMARY KEY ([ID_CARGO], [ID_PERSONA])
go

-- Table PREPARACION

CREATE TABLE [PREPARACION]
(
    [ID_RECETA]   Bigint       NOT NULL,
    [ID_PASO]     Bigint       NOT NULL,
    [DESCRIPCION] VARCHAR(500) NOT NULL
)
go
-- Add keys for table PREPARACION

ALTER TABLE [PREPARACION]
    ADD CONSTRAINT [Unique_Identifier13] PRIMARY KEY ([ID_RECETA], [ID_PASO])
go

-- Table RECETAS_CURSOS

CREATE TABLE [RECETAS_CURSOS]
(
    [ID_RECETA] Bigint NOT NULL,
    [ID_CURSO]  Bigint NOT NULL
)
go

-- Table GRUPO_PERSONAS

CREATE TABLE [GRUPO_PERSONAS]
(
    [ID_GRUPO]   Bigint NOT NULL,
    [ID_PERSONA] Bigint NOT NULL
)
go

-- Create foreign keys (relationships) section ------------------------------------------------- 


ALTER TABLE [RECETAS]
    ADD CONSTRAINT [CATEGORIA_RECETA] FOREIGN KEY ([ID_CATEGORIA]) REFERENCES [CATEGORIAS] ([ID_CATEGORIA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [RECETAS]
    ADD CONSTRAINT [AUTOR_RECETA] FOREIGN KEY ([ID_PERSONA]) REFERENCES [PERSONAS] ([ID_PERSONA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [INGREDIENTES]
    ADD CONSTRAINT [INGREDIENTE_UNIDAD_MEDIDA] FOREIGN KEY ([ID_UNIDAD_MEDIDA]) REFERENCES [UNIDAD_MEDIDA] ([ID_UNIDAD_MEDIDA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [INGREDIENTES]
    ADD CONSTRAINT [PRODUCTO_INGREDIENTE] FOREIGN KEY ([ID_INGREDIENTE]) REFERENCES [PRODUCTOS] ([ID_PRODUCTO]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [INGREDIENTES]
    ADD CONSTRAINT [RECETA_INGREDIENTES] FOREIGN KEY ([ID_RECETA]) REFERENCES [RECETAS] ([ID_RECETA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [PROVEEDOR_PRODUCTO]
    ADD CONSTRAINT [PROVEEDOR_PRECIO] FOREIGN KEY ([ID_PROVEEDOR]) REFERENCES [PROVEEDOR] ([ID_PROVEEDOR]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [PROVEEDOR_PRODUCTO]
    ADD CONSTRAINT [PRODUCTO_PRECIO] FOREIGN KEY ([ID_PRODUCTO]) REFERENCES [PRODUCTOS] ([ID_PRODUCTO]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [GRUPO]
    ADD CONSTRAINT [CURSO_GRUPO] FOREIGN KEY ([ID_CURSO]) REFERENCES [CURSOS] ([ID_CURSO]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [GRUPO]
    ADD CONSTRAINT [GRUPO_PROFESOR] FOREIGN KEY ([ID_PROFESOR]) REFERENCES [PERSONAS] ([ID_PERSONA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [CARGO_PERSONA]
    ADD CONSTRAINT [CARGO_PERSONAS] FOREIGN KEY ([ID_CARGO]) REFERENCES [CARGOS] ([ID_CARGO]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [CARGO_PERSONA]
    ADD CONSTRAINT [PERSONAS_CARGO] FOREIGN KEY ([ID_PERSONA]) REFERENCES [PERSONAS] ([ID_PERSONA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go



ALTER TABLE [PREPARACION]
    ADD CONSTRAINT [RECETA_PREPARACION] FOREIGN KEY ([ID_RECETA]) REFERENCES [RECETAS] ([ID_RECETA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go